//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_manage_RAHUL_SATA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public string Id { get; set; }
        public string Userid { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Short_description { get; set; }
        public string Long_description { get; set; }
        public string Small_img { get; set; }
        public string Large_img { get; set; }
    }
}
